### ISSUE TITLE
Figure out why Github is failing a test that passes on the dev system and should pass on Github

### ISSUE THREAD

**Issue by platypusguy** [platypusguy/jacobin#1]
The test is TestPrintOfCPpart2() in cpParser_test.go, which simply dumps the previously parsed constant pool (CP) entries to stderr. 

After adding some diagnostic info, got this, which is incorrect b/c it does not show the final two CP entries correctly, which are a dynamic and at UTF8 entry (from Github  build and test #221)
```
    cpParser_test.go:867: dynamic CP entry did not appear in logging of CP contents:
        Number of CP entries parsed: 08
        CP entry: 00, type 00 (dummy entry)
        CP entry: 01, type 16 (method type)      description index: 4370
        CP entry: 02, type 18 (invokedynamic)    boostrap index: 4616, name and type: 4609
        CP entry: 03, type 01 (UTF-8 string)     Module
        CP entry: 04, type 19 (module name)      Module
        CP entry: 05, type 20 (package name)     Module
        CP entry: 06, type 00 (dummy entry)
        CP entry: 07, type 00 (dummy entry)
```

The correct output should be:
```
Number of CP entries parsed: 08
CP entry: 00, type 00 (dummy entry)
CP entry: 01, type 16 (method type)      description index: 4370
CP entry: 02, type 18 (invokedynamic)    boostrap index: 4616, name and type: 4609
CP entry: 03, type 01 (UTF-8 string)     Module
CP entry: 04, type 19 (module name)      Module
CP entry: 05, type 20 (package name)     Module
CP entry: 06, type 17 (dynamic)          boostrap index: 4616, name and type: 4609
CP entry: 07, type 01 (UTF-8 string)     Hello
```
(Notice the difference in the last two entries.)

After removing the Module and Package entries to see whether they were causing the problem, got the following output (from  build and test #222):
```
        cpParser_test.go:867: dynamic CP entry did not appear in logging of CP contents:
        Number of CP entries parsed: 06
        CP entry: 00, type 00 (dummy entry)
        CP entry: 01, type 16 (method type)      description index: 4370
        CP entry: 02, type 18 (invokedynamic)    boostrap index: 4616, name and type: 4609
        CP entry: 03, type 01 (UTF-8 string)     Module
        CP entry: 04, type 00 (dummy entry)
        CP entry: 05, type 00 (dummy entry) 
```
So, it's not the previous entries or their position that are causing the problem. Rather, it's the entries of themselves. 

Note: This issue is logged as *JACOBIN-86* on the internal Jacobin task list (kept on YouTrack)

**Comment by texadactyl** [comment]
I reproduced the Github issue on my laptop.  What is common between the 2?  We both run Ubuntu Linux.  Is this a Windows vs Linux thing?

For example, the string terminators in Windows (\r\n) is not the same as Unix/Linux/MacOS (\n).  Is it possible that this is somehow a factor in func parseConstantPool()?

**Comment by texadactyl** [comment]
Hopefully fixed (somehow) with PR #4.  Or, my previous PR somehow cleansed cpParser_test.go of those stupid windoze ```\r``` characters by passing them through my Ubuntu laptop?  Elephino.

**Comment by platypusguy** [comment]
All working properly. The two-bit gods have looked favorably on us! Thanks again!

**Comment by platypusguy** [comment]
Closes PLATYPUS-86 in the task/defect tracker on YouTrack
