### ISSUE TITLE
jacobin failed to recognise class file specified by a.b.c

### ISSUE THREAD

**Issue by texadactyl** [platypusguy/jacobin#13]
Maybe this report is about a feature that is on the jacobin TO-DO list?  If so, pardon my jumping the gun.

Tree-top: scimark2_java, cloned from https://github.com/texadactyl/scimark2_java.
**ls -R** 
```
.:
jnt  LICENSE  original_README.txt  README.md

./jnt:
Bench  scimark2

./jnt/Bench:
Applet.java  Bench.java  Formatter.java  HTTPPost.java  Plotter.java  SendMail.java  Stopwatch.java  SubmitDialog.java  Target.java

./jnt/scimark2:
applet.java        commandline.java  Constants.java  FFT.java     kernel.class  LU.class  MonteCarlo.class  Random.class  SOR.class  SparseCompRow.class  Stopwatch.class
commandline.class  Constants.class   FFT.class       Jacobi.java  kernel.java   LU.java   MonteCarlo.java   Random.java   SOR.java   SparseCompRow.java   Stopwatch.java
```

**Compile:** javac -O jnt/scimark2/commandline.java

**Run the original jvm:** java jnt.scimark2.commandline
```
SciMark 2.0a, elasped time = 27.23s
URL: https://math.nist.gov/scimark2/index.html

Composite Score: 2901.249182054803
FFT (1024): 2033.507015924168
SOR (100x100):   1887.3214307438175
Monte Carlo : 1655.731504772598
Sparse matmult (N=1000, nz=5000): 2590.355516411772
LU (100x100): 6339.33044242166

java.vendor: Private Build
java.version: 11.0.15
java..vm.vendor: Private Build
java.vm.version: 11.0.15+10-Ubuntu-0ubuntu0.22.04.1
os.arch: amd64
os.name: Linux
os.version: 5.15.0-41-generic
```

**Run jacobin (compiled with go 1.8):** jacobin jnt.scimark2.commandline
```
Jacobin VM v. 0.1.0, © 2021-2 by Andrew Binstock. All rights reserved. MPL 2.0 License.
jnt.scimark2.commandline is not a recognized option. Ignored.
```

**Version information:**
openjdk version "11.0.15" 2022-04-19 x64
Xubuntu 22.04 LTS

**Comment by texadactyl** [comment]
Tiny progran:
```
public class hello
{
	public static void main(String args[])
	{
	    System.out.println("Hello, y'all!");
    }
}
```
1. Compile with ```javac hello.java``` - ok
2. Execute with ```java hello``` - ok
3. Execute with ```jacobin hello``` - same error i.e. "hello is not a recognized option. Ignored."

I must be missing something about the jacobin command line.

**Comment by platypusguy** [comment]
Richard: Thanks for trying out Jacobin. Currently, to run a single class, Jacobin requires that the .class extension for the file be specified (this is different from the JDK). We've just started adding JAR support and we will eventually add support for the same CLI scheme for specifying classes that the JDK uses. If you try your class with the .class extension, be aware that some key interpreter instructions still have not been implemented. I'll be happy to look at your results. Again, thank you for trying Jacobin at such an early stage!

**Comment by texadactyl** [comment]
With the above simple program, I saw some unexplainable "Error: could not find" messages at the end of execution.

jacobin hello.class
```
Jacobin VM v. 0.1.0, © 2021-2 by Andrew Binstock. All rights reserved. MPL 2.0 License.
Hello, y'all!
Error: could not find or load main class classes/java/lang/Object.class. Exiting.
Error: could not find or load main class classes/java/lang/System.class. Exiting.
Error: could not find or load main class classes/java/io/PrintStream.class. Exiting.
```

Running jacobin with the original program, I had to first cd into the directory where the commandline.class file is located or specify the path relative to the classpath node: ```jacobin  jnt/scimark2/commandline.class```.  As you suspected, I ran into something that might not yet be supported:
```Invalid bytecode found: 20 at location 0 in method main() of class jnt/scimark2/commandline```
[commandline.class.zip](https://github.com/platypusguy/jacobin/files/9187969/commandline.class.zip)



Yes, I have been "trained" to use the CLI scheme for specifying classes that the JDK uses.  This exercise started with a scientist colleague who is trained in the same way.  

Agreed that the CLI scheme is nonintuitive.  Frankly I have always found the Java compiler and JVM implicit mapping from dots (.) to subdirectory token separators (/) non intuitive.  )-:

**Comment by suresk** [comment]
@texadactyl Thanks for your detailed reports. A couple of questions:

1. How recent is your jacobin build?

2. Do you have JAVA_HOME set?

@platypusguy 

Two things stand out from this:

1. We should figure out some way to bake the commit hash into the version output so we can quickly figure verify the version from reports like this.

2. I think the classloader error is misleading - it isn't the main class we are looking for and we don't exit. I've added a PR to clean this up here - https://github.com/platypusguy/jacobin/pull/14

**Comment by texadactyl** [comment]
@suresk 
1. Built it yesterday.  You can see the version announced in the above file, finest.txt.
2. JAVA_HOME is not set.  Never have needed it.

**Comment by suresk** [comment]
jacobin doesn't currently ship with its own set of Java standard libraries - it has to rely on an existing Java install, which it finds via the JAVA_HOME variable. If you do something like `JAVA_HOME=/path/to/your/java` jacobin hello.class, it should get rid of those error messages. We should add a better error/warning in that case, I thought we did as part of the jmod work I did, but I guess not.

Side note - your example still works (with warnings) because Jacobin implements some standard methods in Go, including `System.out.println`.

**Comment by texadactyl** [comment]
In Linux and Unix, the JAVA_HOME variable is unnecessary for ```java``` and ```javac``` because those executables can find the libraries on their own, a result of installing with apt (E.g. Ubuntu) or rpm (E.g. Fedora).  Yes, when creating a JAVA_HOME environment variable, the jacobin error messages do go away in the hello program.

Baking the commit hash .....

You could have a bash shell script that drives the compile process.  Then you can generate a version file before compiling:
```
# Assuming that you are positioned at the jacobin top of a directory-tree that was git cloned.
VERSION_FILE=./src/globals/version.go
echo "package globals" > $VERSION_FILE
echo "const VERSION string = \""`git describe --tags`"\"" >> $VERSION_FILE
cd src; go build
# How do you folks intend to install?  (-: That work can wait.
```

version.go example:
```
package globals
const VERSION string = "v.0.1.0-proofOfConcept-146-gb51b3b7"
```
globals/global.go would be modified to import the value from version.go and use it in ```func InitGlobals``` instead of manually editing ```Version:           "0.1.0"```.

A Windows .cmd/.bat file should be similar.  I tested the above on Linux but I have no access to Windows.  (:

**Comment by suresk** [comment]
I ended up with a slightly different approach using ldflags - https://github.com/platypusguy/jacobin/compare/main...suresk:jacobin:git-stamp

I also added a Makefile - that is probably a bit more cross-platform compatible?

Curious what you two think about this - it ends up with this output:

`Jacobin VM v. 0.1.0 (git: git-stamp @ 9b09091), © 2021-2 by Andrew Binstock. All rights reserved. MPL 2.0 License.
Hello, y'all!`

**Comment by texadactyl** [comment]
@suresk @platypusguy 

In 2022, we could come up with a better solution than ```make```.  Don't get me wrong, I have many fond memories of developing with C/C++/make on Unix/Linux.

How about this wild & crazy idea:  Replace my bash script with a small golang program, in a tree parallel to "src".  This will eventually be the jacobin installation "script".

Advantages:
* 100% portable.
* Go language is required anyways for the "src" subdirectory tree.

Reactions?

**Comment by suresk** [comment]
`make` may be old, but current tooling supports it well and it is quite common to see it used in Go projects.

I don't have strong feelings about `make`, but I am personally not overly excited about maintaining a custom build tool without a compelling reason.

**Comment by platypusguy** [comment]
Richard: Thanks again for pursuing the testing of your class with Jacobin and providing all this valuable feedback. 

Spencer: Thanks for the PR, which I've integrated to the codebase and added to the tracker as JACOBIN-185. 

Perhaps one way to solve the build # issue is to do what the JDK does: include the build date (see: `java -version`) I'm partial to not getting involved in complex builds yet (I suspect they're inevitable in the long run) and I pray to the gods that we won't need to use `make`. My life post-C has been delightfully free of debugging make scripts. I've opened JACOBIN-186 for this issue. (Richard, if you're interested in access to the feature and defect tracker, let me know and I'll get you access. It's on JetBrains YouTrack, which has worked out very nicely.)

**Comment by suresk** [comment]
I never did much C/C++ in a professional setting, so maybe that's why I'm not gunshy about `make` :) Our Golang devs at work introduced it and most open-source Golang projects I've come across it use it, so it seemed like a reasonable first shot.

I don't like the date as much, because you have to map it back to a release and we aren't really doing those right now? Being able to place it at a specific commit is really useful for debugging as we are building it. That said, I found something better! It looks like a BuildInfo package was added in go 1.18 and as part of the normal `go build` process you get a bunch of useful stuff - https://pkg.go.dev/debug/buildinfo

It looks like only the commit hash is in there, not the branch, but that's ok because you can easily find it. So we can include that (plus the date/time if we want) without any changes to the build. If that sounds good, I'll get a PR up for it tomorrow.

**Comment by texadactyl** [comment]
@suresk @platypusguy Currently have Dutch family staying with me (Andrew - remember Ietje's sister Maria?).  So I will be distracted from computer stuff mostly.

**Comment by texadactyl** [comment]
Closing as I believe the original issue has been explained.
