### ISSUE TITLE
func Log and func shutdown contain a local mutex

### ISSUE THREAD

**Issue by texadactyl** [platypusguy/jacobin#2]
As written, I believe that simultaneous threads will never wait because the mutex variable is local to functions being called.

Guessing from a Go newbie but I believe that you wanted to do something like this:  https://notes.shichao.io/gopl/ch9/#mutual-exclusion-syncmutex and move the mutex definition to be global to the log package?

Those are the only 2 cases (logger.go:Log & main.go:shutdown) that I saw where there are mutexes being used.

**Comment by texadactyl** [comment]
Also, why are you protecting a Log call in shutdown when Log protects itself?

**Comment by platypusguy** [comment]
Your edits merged. A big thank you! Now closing this issue.
