### ISSUE TITLE
[QUESTION] Java 21 class support

### ISSUE THREAD

**Issue by Mcbencrafter** [platypusguy/jacobin#234]
Hi,
do you plan on adding support for Java 21 classes in the future?
I've read your blog and like the idea of a JVM in go. I would love to use the jvm when there is a stable release at some point. But since some projects of mine are based on Java 21, Java 21 class support would be really nice. It would probably also be an incentive for more people to try out the jvm, because Java 17 is already a few years old by now.

**Comment by platypusguy** [comment]
Benjamin: Thanks for your inquiry and for your kind words. Presently, all our internal testing is done with JDK 21, so we are capable of running Java 21 classes. What we don't do is deliver the new features in Java 21 yet. 

Nonetheless, you make good point that we should state that we run Java 21 classes. I will update accordingly.

Thanks again!
