### ISSUE TITLE
Wrong value printed

### ISSUE THREAD

**Issue by oflebbe** [platypusguy/jacobin#66]
run the code (compiled with Temurin 17, these classes are used with JAVA_HOME for jacobin as well)

With Temurin Output is 42, with Jacobin 0.

```
final class A {
   static int x = 42;

   public static void main( String argv[]) {
     System.out.println(x);
   }
}
```
No warning or error message is shown while running jacobin

**Comment by platypusguy** [comment]
Thanks for the report. That's odd. Will get on it right away.

**Comment by platypusguy** [comment]
We completed the initial implementation of static initialization blocks. And now your test works correctly. Unless you object, we'll move the code into our test suite to make sure there are no regressions. Again, thank you!
