### ISSUE TITLE
Local mutex makes no sense

### ISSUE THREAD

**Issue by avpavlov** [platypusguy/jacobin#8]
Local mutex does not make sense

https://github.com/platypusguy/jacobin/blob/8818d325dae39b9a8a427359bd36ef330067e179/src/thread/jvmThread.go#L36

shouldn't it be

```
var addThreadToTableMutex = sync.Mutex{}
func AddThreadToTable(t *ExecThread, tbl *list.List) int {
	addThreadToTableMutex .Lock()

	tbl.PushBack(t)
	t.ID = tbl.Len() - 1
	addThreadToTableMutex .Unlock()

	return t.ID
}
```

**Comment by platypusguy** [comment]
Sorry for the delay in responding. You're absolutely right. &#128563; I think the mutex should actually be place in the `tbl` into which the thread is being added. I'll get this fixed. Thank you for catching this!

**Comment by platypusguy** [comment]
Tests written and passing (JACOBIN-168). So, closing this. Thanks again for bringing it to our attention!
